-- 所有的站点
CREATE TABLE IF NOT EXISTS public.mb_site (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name TEXT PRIMARY KEY,
  title TEXT,
  content TEXT,
  detail TEXT,
  url TEXT,
  image_url TEXT,
  thumbnail_url TEXT,
  website_data TEXT,
  create_time TIMESTAMPTZ,
  update_time TIMESTAMPTZ,
  rating INTEGER,
  tag_name TEXT,
  category_name TEXT,
  click_count integer default 0,
  like_count integer default 0,
  fav_count integer default 0,
  submit_by TEXT,
  status integer default 1
) TABLESPACE pg_default;



-- 添加注释
comment on column public.site.rating is '平均评分';
comment on column public.site.like_count is '点赞数';
comment on column public.site.click_count is '使用数';
comment on column public.site.fav_count is '收藏数';
comment on column public.site.submit_by is '提交人';
comment on column public.site.status is '0-不展示; 1-正常展示';

-- 用户提交的站点
CREATE TABLE IF NOT EXISTS public.submit_site (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
  submit_time timestamp with time zone NOT NULL DEFAULT now(),
  name text NULL,
  url text NOT NULL UNIQUE,
  email text NULL,
  is_feature integer default 0,
  priority integer default 1,
  status integer default 0
) TABLESPACE pg_default;
-- 查询submit表，按提交时间，status=0（未处理），按照is_feature desc, priority desc, created_at asc
-- 得到结果后，写入site，同时修改submit的status=1



-- 添加注释
comment on column public.submit_site.status is '0-未处理; 1-已处理';
comment on column public.submit_site.priority is '优先级.越高越先处理。0-不处理';



-- 用户
CREATE TABLE IF NOT EXISTS public.mb_user (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
  user_id TEXT NOT NULL UNIQUE,
  name text NULL,
  email text NULL,
  pwd text NULL,
  mobile text NULL,
  source text NULL,
  status integer default 1,
  type integer default 0,
  thumbnail_url text null,
  create_time timestamp with time zone NOT NULL DEFAULT now(),
) TABLESPACE pg_default;



-- 添加注释
comment on column public.user.status is '0-删除; 1-正常';
comment on column public.user.type is '0-正常用户; 1-付费用户; 9-admin';



